import { __extends, __decorate } from "tslib";
window.__extends = __extends;
window.__decorate = __decorate;
import "socket.io-client";
import "qrcode";
import "clipboard";
import "file-uploader-vue-component";
import "webrtc-adapter/out/adapter_no_edge_no_global";
import "vue";
import "vue-class-component";
import "js-split-file/browser";
