import { __extends, __decorate } from "tslib";
(global as any).__extends = __extends;
(global as any).__decorate = __decorate;
import "socket.io-client";
import "qrcode";
import "clipboard";
import "file-uploader-component/dist/vue";
import "webrtc-adapter/out/adapter_no_edge_no_global";
import "vue";
import "vue-class-component";
import "js-split-file/browser";
import "date-fns/format";
